services:
  pgvector:
    image: pgvector/pgvector:pg18-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data/:/var/lib/postgresql
    ports:
      - ${DB_PORT}:5432
